version: '3.4'

services:
  odoo:
    image: odoo16
    container_name: odoo16
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5678:5678"
      - "80:8069"
    volumes:
      - ./odoo:/odoo/
      - Odoo16:/var/lib/odoo
    command: [
        "sh", 
        "-c", 
        "pip3 install debugpy -t /tmp && /entrypoint.sh python3 /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 /odoo/odoo-server/odoo-bin --dev=all"
      ]
  db:
    image: postgres:12
    container_name: odoo16_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - Odoo16DB:/var/lib/postgresql/data

volumes:
  Odoo16:
  Odoo16DB: